# Generated by Django 2.1.5 on 2019-09-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='area_hetcha',
            new_name='area_hectares',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='state',
            new_name='states',
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
